import { useAuth0 } from '@auth0/auth0-react'
import { useEffect, useState } from 'react'
import { Link } from 'react-router-dom'

import ErrorMessage from '../components/ErrorMessage'
import LoadingSpinner from '../components/LoadingSpinner'
import { getJson } from '../utils/apiClient'
import { buildCoursePath } from '../utils/routeHelpers'

function MyCoursesPage() {
  const { getAccessTokenSilently } = useAuth0()
  const [courses, setCourses] = useState([])
  const [isLoading, setIsLoading] = useState(true)
  const [error, setError] = useState('')

  useEffect(() => {
    const loadMyCourses = async () => {
      try {
        setIsLoading(true)
        setError('')

        const token = await getAccessTokenSilently()
        const response = await getJson('/me/courses', { accessToken: token })
        setCourses(Array.isArray(response.data) ? response.data : [])
      } catch (requestError) {
        setError(requestError.message || 'Failed to load your courses')
      } finally {
        setIsLoading(false)
      }
    }

    loadMyCourses()
  }, [getAccessTokenSilently])

  if (isLoading) {
    return <LoadingSpinner label="Loading your courses..." />
  }

  if (error) {
    return <ErrorMessage message={error} />
  }

  return (
    <section className="space-y-4">
      <header className="space-y-1">
        <h2 className="text-2xl font-bold text-white">My Courses</h2>
        <p className="text-sm text-slate-300">Courses generated by your account.</p>
      </header>

      <div className="grid grid-cols-1 gap-3 sm:grid-cols-2">
        {courses.map((course) => (
          <Link
            key={course.id}
            to={buildCoursePath(course.id)}
            className="rounded-lg border border-slate-700 bg-slate-900 px-4 py-3 text-sm text-slate-200 hover:border-indigo-500 hover:text-indigo-300"
          >
            {course.title}
          </Link>
        ))}

        {courses.length === 0 && <p className="text-sm text-slate-400">No claimed courses yet.</p>}
      </div>
    </section>
  )
}

export default MyCoursesPage
